apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: luios1baw-go 
  janus-idp.io/tekton: luios1baw-go
  backstage.io/kubernetes-id: luios1baw-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: luios1baw-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml