apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: luios1baw-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: luios1baw-go 
  name: luios1baw-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: luios1baw-go 
